### PR TITLE
Enhanced .js file to show Turn button only if back content exists and remove extra space when image does not exist

### PR DESCRIPTION
**Pull request by supriyarajgopal-spi**

### CODE REVIEW

**Comment by thomasmars** [comment]
What is the difference between this pull request and #7 ? Can one of them be closed ? There seems to be a lot of similarities between them.

**Comment by supriyarajgopal-spi** [comment]
@thomasmars , hi.
If a back image is not specified, then it means that both front and back cards are same. So, having a Turn button makes no sense.
The only difference between this and PR #7  is that the 'Turn' button on the dialogcard will be shown only if there is a different image on the back of the card.

**Comment by thomasmars** [comment]
If they are almost identical can you please close one of them ? :)

**Comment by supriyarajgopal-spi** [comment]
Ok @thomasmars , I am going to close this one.
I am working on your suggestions on #7 . Will include this feature also and commit to #7.

Thank you.

**Pull request closed without merging**
