### PR TITLE
add German translation

### PR DESCRIPTION
**Pull request by otacke**

### CODE REVIEW

**Comment by timothyylim** [comment]
Hi @otacke, would you like to test out transifex with this translation? Head over to 

https://www.transifex.com/h5p/h5p-dialogcards

Once you've inputted the translations there, I'll pull them into the transifex branch of dialogcards, then if the rest of the Core Team are happy with the workflow, I'll merge it into master. 

😸

**Comment by otacke** [comment]
Sure! I will be back home from a business trip tomorrow and have a look then.

**Comment by timothyylim** [comment]
I've pulled your translations from transifex instead :)

**Comment by otacke** [comment]
Alright! I'm running out of open pull requests. I guess I'll have to code more quickly ;-)

**Pull request closed without merging**
